algoritmo "gasolina"

var
   gaso: real
   litro:real
   con:real
   via:real

inicio
   gaso <- 5.50
   con <- (358/10)
   via <- 358


  escreval("-----------------------------------------------")
  escreval("CALCULE O PREÇO DA VIAGEM")
  escreval("-----------------------------------------------")

  litro <- (gaso*con)

  escreva("VOCÊ VAI GASTAR:", litro)


fimalgoritmo
